### ISSUE TITLE
Lag when checking recipes in ME terminals

### ISSUE THREAD

**Issue by Renno231** [vfyjxf/NotEnoughEnergistics#28]
Over the course of making a few dozen patterns, I've noticed that when checking the recipe of an item or checking what the item can be used for, there is frequent game-freezing lag for at least half a second and in some cases 2-3 seconds. I'm fairly certain that it's this mod because the modpack I'm on didn't have this issue in the ME terminals until Just Enough Energistics was swapped for Not Enough Energistics.

**Comment by vfyjxf** [comment]
Because NotEnoughEnergistics those functions related to synthesis, as well as the highlighting of missing materials, need to get data from ae to retrieve, but some recipes, such as those for designing boards or sticks, which may have a lot of items in their OreDictionarys, as well as some problems with the current algorithm implementation, lead to lagging problems.
This issue was actually fed back in #27, but I haven't had time to fix it in recent months, as well as I plan to rewrite the entire NotEnoughEnergistics this month, so a fix for this issue may have to wait a while before it is fixed.

**Comment by vfyjxf** [comment]
It will be fixed in NEE 2.x .

**Comment by acelel** [comment]
I've been having the same thing happen to me on 2.0.2
