### ISSUE TITLE
NotEnoughEnergistics completely breaks without crash/error  reporting

### ISSUE THREAD

**Issue by Renno231** [vfyjxf/NotEnoughEnergistics#29]
While playing on a server, it seems that my ability to press the + button in a recipe and have it fill the pattern terminal is no longer effective. All of the features related to the pattern terminal that NotEnoughEnergistics boasts are no longer working. I've relaunched my pack several times, removed all things related to the mod, redownloaded the mod, and even restarted my PC and the server I play on. There is/was no discernable event that caused this to happen. There seems to be no mention of anything happening with the mod in the logs. Notably, the mod still works for other people on the server. I had them send over their configs, and all of them are identical. 

I further tested this in single-player; weirdly enough, it still seems to work in single-player worlds.

Edit: I created a fresh profile of the mod pack, went through the modlist, and found JustEnoughEnergistics in the mod list despite having deleted it. By deleting it once again, it seems that the mods features have been returned.

**Comment by vfyjxf** [comment]
The reason for this problem is that JustEnoughEnergistics and NotEnoughEnergistics both use the same method to replace the AE's logic, and because of the order in which the JEI Plugin is loaded, JustEnoughEnergistics may have replaced NotEnoughEnergistics' logic after NotEnoughEnergistics has replaced it.
